/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JDialog.java to edit this template
 */
package Apresentacao;

import Controladores.Locadora;
import Modelo.Bicicleta;
import Modelo.Cliente;
import Modelo.Veiculo;
import java.awt.event.MouseAdapter;
import java.awt.event.MouseEvent;
import java.util.ArrayList;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author Yan
 */
public class DlgMostraBicicletas extends javax.swing.JDialog {

    /**
     * Creates new form DlgMostrarBicicletas
     */
    Locadora l;
    
    public DlgMostraBicicletas(java.awt.Frame parent, boolean modal) {
        super(parent, modal);
        initComponents();
    }
    public DlgMostraBicicletas(java.awt.Frame parent, boolean modal, Locadora l) {
        super(parent, modal);
        this.l = l;
        initComponents();
        exibeInformacoes();
        DlgMostraBicicletas self = this; // Referência para a instância atual da janela
        // Adicionando o evento de clique à tabela de bicicletas
        jTbikes.addMouseListener(new MouseAdapter() {
            public void mouseClicked(MouseEvent e) {
                if (e.getClickCount() == 2) { // Verifica o clique duplo
                    int selectedRow = jTbikes.getSelectedRow();
                    if (selectedRow != -1) { // Garante que uma linha foi selecionada
                        Veiculo veiculoSelecionado = l.listarVeiculos().get(selectedRow);
                        self.dispose();
                        // Abre a tela de edição com os dados do veículo selecionado
                        DlgEditarVeiculo telaEdicao = new DlgEditarVeiculo(null, true, veiculoSelecionado);
                        telaEdicao.setVisible(true);

                        // Aqui você pode recarregar os dados na tabela após a edição, se necessário
                        // exibeInformacoes();
                    }
                }
            }
        });
        exibeInformacoes();
    }

    private void exibeInformacoes() {
        ArrayList<Veiculo> bicicletas = l.listarVeiculos();

        // Defina o número de linhas na tabela com base na quantidade de bicicletas
        DefaultTableModel model = (DefaultTableModel) jTbikes.getModel();
        model.setRowCount(bicicletas.size());

        int bikeIndex = 0; // Índice para controlar a inserção das bicicletas na tabela

        for (Veiculo veiculo : bicicletas) {
            if (veiculo instanceof Bicicleta) {
                Bicicleta bicicleta = (Bicicleta) veiculo;

                // Preencha as colunas da tabela com as informações da bicicleta
                jTbikes.setValueAt("Bicicleta", bikeIndex, 0);
                jTbikes.setValueAt(bicicleta.getIdVeiculo(), bikeIndex, 1);
                jTbikes.setValueAt(bicicleta.getModelo(), bikeIndex, 2);
                jTbikes.setValueAt(bicicleta.getCor(), bikeIndex, 3);
                jTbikes.setValueAt(bicicleta.getMarca(), bikeIndex, 4);
                jTbikes.setValueAt(bicicleta.getValorDia(), bikeIndex, 5);
                jTbikes.setValueAt(bicicleta.getTipoBicicleta(), bikeIndex, 6);

                bikeIndex++; // Avance para a próxima linha da tabela para a próxima bicicleta
            }
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();
        jTbikes = new javax.swing.JTable();
        jLabel1 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);

        jTbikes.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null}
            },
            new String [] {
                "Tipo", "id", "Modelo", "Marca", "Cor", "Valor Diária", "Tipo Bicicleta"
            }
        ));
        jTbikes.setToolTipText("");
        jScrollPane1.setViewportView(jTbikes);

        jLabel1.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel1.setText("Bicicletas Cadastradas");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 690, Short.MAX_VALUE)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 310, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(0, 0, Short.MAX_VALUE)))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 445, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(DlgMostraBicicletas.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(DlgMostraBicicletas.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(DlgMostraBicicletas.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(DlgMostraBicicletas.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the dialog */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                DlgMostraBicicletas dialog = new DlgMostraBicicletas(new javax.swing.JFrame(), true);
                dialog.addWindowListener(new java.awt.event.WindowAdapter() {
                    @Override
                    public void windowClosing(java.awt.event.WindowEvent e) {
                        System.exit(0);
                    }
                });
                dialog.setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel jLabel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable jTbikes;
    // End of variables declaration//GEN-END:variables
}
