/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package Apresentacao;

import Controladores.ControladorCliente;
import Controladores.Locadora;
import Controladores.ControladorAluguel;
import Modelo.Aluguel;
import java.util.ArrayList;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author Yan
 */
public class TelaInicial extends javax.swing.JFrame {

    /**
     * Creates new form TelaInicial
     */

    Locadora locadora = Locadora.getInstance();
    ControladorCliente controladorcliente = ControladorCliente.getInstance();
    ControladorAluguel controladorAluguel = ControladorAluguel.getInstance();

    public TelaInicial() {
        initComponents();
        exibeInformacoes();
        
    }
    private void exibeInformacoes() {
        DefaultTableModel model = (DefaultTableModel) jTalugueis.getModel();
        model.setRowCount(0); // Limpa a tabela para inserir os novos dados
        ArrayList<Aluguel> alugueis = controladorAluguel.listarAluguel();
        
        for (Aluguel aluguel : alugueis) {
            Object[] rowData = {
                aluguel.getIdAluguel(),
                aluguel.getDataIni(),
                aluguel.getDataFim(),
                aluguel.getVeiculo().getIdVeiculo(),
                aluguel.getCliente().getCpf(),
                (aluguel.getSeguro() != null) ? aluguel.getSeguro().getNomeSeguro() : "Não se aplica"
            };
            model.addRow(rowData); // Adiciona uma nova linha com os dados do aluguel
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jScrollPane3 = new javax.swing.JScrollPane();
        jTalugueis = new javax.swing.JTable();
        jLabel1 = new javax.swing.JLabel();
        jMenuBar1 = new javax.swing.JMenuBar();
        jMareafunc = new javax.swing.JMenu();
        jMcadfunc = new javax.swing.JMenuItem();
        jMlistarfunc = new javax.swing.JMenuItem();
        jMclientes = new javax.swing.JMenu();
        jMcadastrarcliente = new javax.swing.JMenuItem();
        jMlistarclientes = new javax.swing.JMenuItem();
        jMalugueis = new javax.swing.JMenu();
        jMnovoaluguel = new javax.swing.JMenuItem();
        jMlistaralugueis = new javax.swing.JMenuItem();
        jMpagamento = new javax.swing.JMenuItem();
        jMveiculos = new javax.swing.JMenu();
        jmiCadastroAuto = new javax.swing.JMenuItem();
        jmiBici = new javax.swing.JMenuItem();
        jmiListarAuto = new javax.swing.JMenuItem();
        jMilistarBici = new javax.swing.JMenuItem();
        jMsair = new javax.swing.JMenu();
        jMencerrar = new javax.swing.JMenuItem();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setBackground(new java.awt.Color(255, 0, 0));

        jTalugueis.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null}
            },
            new String [] {
                "idAluguel", "DataIni", "DataFim", "idVeiculo", "idCliente", "TipoSeguro", "StatusPag"
            }
        ));
        jTalugueis.setToolTipText("");
        jScrollPane3.setViewportView(jTalugueis);

        jLabel1.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel1.setText("GERENCIADOR DE ALUGUÉIS");

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel1)
                .addContainerGap(636, Short.MAX_VALUE))
            .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(jPanel1Layout.createSequentialGroup()
                    .addContainerGap()
                    .addComponent(jScrollPane3, javax.swing.GroupLayout.DEFAULT_SIZE, 822, Short.MAX_VALUE)
                    .addContainerGap()))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 29, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 468, Short.MAX_VALUE))
            .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(jPanel1Layout.createSequentialGroup()
                    .addGap(38, 38, 38)
                    .addComponent(jScrollPane3, javax.swing.GroupLayout.PREFERRED_SIZE, 420, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addContainerGap(39, Short.MAX_VALUE)))
        );

        jMenuBar1.setBackground(new java.awt.Color(120, 120, 120));
        jMenuBar1.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jMenuBar1.setPreferredSize(new java.awt.Dimension(321, 50));
        jMenuBar1.setRequestFocusEnabled(false);

        jMareafunc.setText("Área do Funcionário");
        jMareafunc.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N

        jMcadfunc.setText("Cadastrar Funcionário");
        jMcadfunc.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMcadfuncActionPerformed(evt);
            }
        });
        jMareafunc.add(jMcadfunc);

        jMlistarfunc.setText("Listar Funcionários");
        jMlistarfunc.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMlistarfuncActionPerformed(evt);
            }
        });
        jMareafunc.add(jMlistarfunc);

        jMenuBar1.add(jMareafunc);

        jMclientes.setText("Clientes");
        jMclientes.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N

        jMcadastrarcliente.setText("Cadastrar Cliente");
        jMcadastrarcliente.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMcadastrarclienteActionPerformed(evt);
            }
        });
        jMclientes.add(jMcadastrarcliente);

        jMlistarclientes.setText("Listar Clientes");
        jMlistarclientes.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMlistarclientesActionPerformed(evt);
            }
        });
        jMclientes.add(jMlistarclientes);

        jMenuBar1.add(jMclientes);

        jMalugueis.setText("Aluguéis");
        jMalugueis.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N

        jMnovoaluguel.setText("Novo Aluguel");
        jMnovoaluguel.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMnovoaluguelActionPerformed(evt);
            }
        });
        jMalugueis.add(jMnovoaluguel);

        jMlistaralugueis.setText("Listar Aluguéis");
        jMlistaralugueis.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMlistaralugueisActionPerformed(evt);
            }
        });
        jMalugueis.add(jMlistaralugueis);

        jMpagamento.setText("Pagamento");
        jMpagamento.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMpagamentoActionPerformed(evt);
            }
        });
        jMalugueis.add(jMpagamento);

        jMenuBar1.add(jMalugueis);

        jMveiculos.setText("Veículos");
        jMveiculos.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N

        jmiCadastroAuto.setText("Cadastrar Automóvel");
        jmiCadastroAuto.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jmiCadastroAutoActionPerformed(evt);
            }
        });
        jMveiculos.add(jmiCadastroAuto);

        jmiBici.setText("Cadastrar Bicicleta");
        jmiBici.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jmiBiciActionPerformed(evt);
            }
        });
        jMveiculos.add(jmiBici);

        jmiListarAuto.setText("Listar Automóveis");
        jmiListarAuto.setToolTipText("");
        jmiListarAuto.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jmiListarAutoActionPerformed(evt);
            }
        });
        jMveiculos.add(jmiListarAuto);

        jMilistarBici.setText("Listar Bicicletas");
        jMilistarBici.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMilistarBiciActionPerformed(evt);
            }
        });
        jMveiculos.add(jMilistarBici);

        jMenuBar1.add(jMveiculos);

        jMsair.setText("Sair");
        jMsair.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N

        jMencerrar.setText("Encerrar Sessão");
        jMencerrar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMencerrarActionPerformed(evt);
            }
        });
        jMsair.add(jMencerrar);

        jMenuBar1.add(jMsair);

        setJMenuBar(jMenuBar1);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jMcadfuncActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMcadfuncActionPerformed
        // TODO add your handling code here:
        DlgCadastroFuncionario telaCadastro = new DlgCadastroFuncionario(null, true, locadora);
        telaCadastro.setVisible(true);
    }//GEN-LAST:event_jMcadfuncActionPerformed

    private void jMlistarclientesActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMlistarclientesActionPerformed
        // TODO add your handling code here:
        DlgMostraClientes dlg = new DlgMostraClientes(null, true, controladorcliente);
        dlg.setVisible(true);
    }//GEN-LAST:event_jMlistarclientesActionPerformed

    private void jMcadastrarclienteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMcadastrarclienteActionPerformed
        // TODO add your handling code here:
        DlgCadastroCliente telaCadastroCli = new DlgCadastroCliente(null, true, controladorcliente);
        telaCadastroCli.setVisible(true);
    }//GEN-LAST:event_jMcadastrarclienteActionPerformed

    private void jMencerrarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMencerrarActionPerformed
        // TODO add your handling code here:
        TelaLogin telaLogin = new TelaLogin(locadora);
        telaLogin.setVisible(true);   
        this.dispose();     
    }//GEN-LAST:event_jMencerrarActionPerformed

    private void jMlistarfuncActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMlistarfuncActionPerformed
        // TODO add your handling code here:
        DlgMostraFuncionarios dlg = new DlgMostraFuncionarios(null, true, locadora);
        dlg.setVisible(true);
    }//GEN-LAST:event_jMlistarfuncActionPerformed

    private void jmiBiciActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jmiBiciActionPerformed
        // TODO add your handling code here:
        DlgCadastroBicicleta dlg = new DlgCadastroBicicleta(null, true, locadora);
        dlg.setVisible(true);       
    }//GEN-LAST:event_jmiBiciActionPerformed

    private void jmiCadastroAutoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jmiCadastroAutoActionPerformed
        // TODO add your handling code here:
        DlgCadastroAutomovel dlg = new DlgCadastroAutomovel(null, true, locadora);
        dlg.setVisible(true);  
    }//GEN-LAST:event_jmiCadastroAutoActionPerformed

    private void jmiListarAutoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jmiListarAutoActionPerformed
        // TODO add your handling code here:
        DlgMostraAutomoveis dlg = new DlgMostraAutomoveis(null, true, locadora);
        dlg.setVisible(true);  
    }//GEN-LAST:event_jmiListarAutoActionPerformed

    private void jMilistarBiciActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMilistarBiciActionPerformed
        // TODO add your handling code here:
        DlgMostraBicicletas dlg = new DlgMostraBicicletas(null, true, locadora);
        dlg.setVisible(true);  
    }//GEN-LAST:event_jMilistarBiciActionPerformed

    private void jMnovoaluguelActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMnovoaluguelActionPerformed
            // TODO add your handling code here:
        DlgCadastroAluguel dlg = new DlgCadastroAluguel(null, true, controladorAluguel);
        dlg.setVisible(true);  
    }//GEN-LAST:event_jMnovoaluguelActionPerformed

    private void jMlistaralugueisActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMlistaralugueisActionPerformed
        // TODO add your handling code here:
        DlgMostraAlugueis mostraAlugueis = new DlgMostraAlugueis(null, true, controladorAluguel);
        mostraAlugueis.setVisible(true);
    }//GEN-LAST:event_jMlistaralugueisActionPerformed

    private void jMpagamentoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMpagamentoActionPerformed
        // TODO add your handling code here:
        DlgCadastroPagamento cadastropag = new DlgCadastroPagamento(null, true, controladorAluguel);
        cadastropag.setVisible(true);     
    }//GEN-LAST:event_jMpagamentoActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(TelaInicial.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(TelaInicial.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(TelaInicial.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(TelaInicial.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new TelaInicial().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel jLabel1;
    private javax.swing.JMenu jMalugueis;
    private javax.swing.JMenu jMareafunc;
    private javax.swing.JMenuItem jMcadastrarcliente;
    private javax.swing.JMenuItem jMcadfunc;
    private javax.swing.JMenu jMclientes;
    private javax.swing.JMenuItem jMencerrar;
    private javax.swing.JMenuBar jMenuBar1;
    private javax.swing.JMenuItem jMilistarBici;
    private javax.swing.JMenuItem jMlistaralugueis;
    private javax.swing.JMenuItem jMlistarclientes;
    private javax.swing.JMenuItem jMlistarfunc;
    private javax.swing.JMenuItem jMnovoaluguel;
    private javax.swing.JMenuItem jMpagamento;
    private javax.swing.JMenu jMsair;
    private javax.swing.JMenu jMveiculos;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane3;
    private javax.swing.JTable jTalugueis;
    private javax.swing.JMenuItem jmiBici;
    private javax.swing.JMenuItem jmiCadastroAuto;
    private javax.swing.JMenuItem jmiListarAuto;
    // End of variables declaration//GEN-END:variables
}
